### ISSUE TITLE
Loop check doesn't seem to work

### ISSUE THREAD

**Issue by dnowatsc** [dgonzal/SFrameBatch#13]
Hi Daniel,
I checked out the latest version of SFrameBatch from the master branch (so after commit ee41cf7) and the loop check doesn't seem to work anymore. So when I start my jobs with 'sframe_batch -sl CONFIG.xml' it does everything correctly (splitting the config files, submitting the jobs etc.) but it doesn't produce the output on the terminal about which jobs are finished, which fraction of the overall sample is completed etc.

**Comment by dnowatsc** [comment]
Update: I see the loop-check output (so where the completed and uncompleted jobs are compared) after re-submitting, but only once (so when I'm running sframe_batch.py -r CONFIG.xml)

**Comment by dgonzal** [comment]
the code in sframe_batch has been restructered and I set the -l option to 'quiet'.  It was/is _technically_ working. But I see that it can be helpful to get a bit more information, so it is now  back to printing every 30 sec in commit  d231681.

there is still some stuff to come since it can happen that sframe_batch tries merging files that are not completely transferred to disk if using -l -m
